### PR TITLE
revert: restore previous API structure

### PR DESCRIPTION
**Pull request by G-Bro**

### CODE REVIEW

**Comment by G-Bro** [comment]
@DanEvans485 this is the way I want the API controllers to be. They all extend a root controller that has a predefined set of methods, list, retrieve create, etc. That way we can guarantee that all models can be accessed and edited in the same way.

**Comment by DanEvans485** [comment]
I don't have an issue with a base ApiController I just deleted the original one and started from scratch to make sure the Player / Monster / Character works properly.
Also you changed the PlayerController $model_class to Monster. Not sure why retrieve is better than get either but meh.

**Comment by G-Bro** [comment]
get can be confusing when you have GET requests and get requests

**Comment by DanEvans485** [comment]
But... It gets something. Wut eva

**Comment by G-Bro** [comment]
It retrieves something too 😁 

also thats the language Stripe uses and I ❤️ sripe

**Comment by DanEvans485** [comment]
Stripe *feels sick*.

**Comment by DanEvans485** [comment]
I think I want a thing from the server so I need to get it. Retrieve sounds weird.

**Pull request merged**
